#!/usr/bin/env bash
# ============================================================================
# regenerate-readme-table.sh
# Rebuilds the plugin table in README.md between the sentinel markers
#   <!-- BEGIN-PLUGIN-TABLE -->  ...  <!-- END-PLUGIN-TABLE -->
# Reads metadata from each plugins/*/.claude-plugin/plugin.json.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PLUGINS_DIR="$REPO_ROOT/plugins"
README="$REPO_ROOT/README.md"
TMP="$(mktemp)"

read_str() {
    grep -E "\"$2\"[[:space:]]*:" "$1" \
        | head -1 \
        | sed -E 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*"([^"]*)".*/\1/'
}

read_str_array() {
    grep -E "\"$2\"[[:space:]]*:[[:space:]]*\[" "$1" \
        | head -1 \
        | sed -E 's/.*"'"$2"'"[[:space:]]*:[[:space:]]*\[([^]]*)\].*/\1/' \
        | tr -d ' "'
}

# Badge → emoji glyph for the README table. Keep these stable.
badge_glyph() {
    case "$1" in
        command) echo "🧠 cmd" ;;
        agent)   echo "🤖 agent" ;;
        hook)    echo "🪝 hook" ;;
        mcp)     echo "🔌 mcp" ;;
        script)  echo "🛠 script" ;;
        skill)   echo "📖 skill" ;;
        *)       echo "$1" ;;
    esac
}

derive_badge_cell() {
    local plugin_dir="$1"
    local out=""
    [ -d "$plugin_dir/commands" ]            && out="$out $(badge_glyph command)"
    [ -d "$plugin_dir/agents" ]              && out="$out · $(badge_glyph agent)"
    [ -f "$plugin_dir/hooks/hooks.json" ]    && out="$out · $(badge_glyph hook)"
    [ -f "$plugin_dir/.mcp.json" ]           && out="$out · $(badge_glyph mcp)"
    [ -d "$plugin_dir/scripts" ]             && out="$out · $(badge_glyph script)"
    [ -f "$plugin_dir/SKILL.md" ]            && out="$out · $(badge_glyph skill)"
    echo "${out# }"
}

declare -a CATEGORIES=(backend frontend gamedev security blueteam reverse productivity systems compliance)

emit_table() {
    {
        echo "<!-- BEGIN-PLUGIN-TABLE -->"
        echo "<!-- Auto-generated by scripts/regenerate-readme-table.sh. Do not edit by hand. -->"
        echo ""
        echo "**Badges legend:** 🧠 slash command · 🤖 sub-agent · 🪝 hook · 🔌 MCP · 🛠 executable script · 📖 SKILL.md"
        echo ""

        for cat in "${CATEGORIES[@]}"; do
            local cat_label
            case "$cat" in
                backend)      cat_label="Backend" ;;
                frontend)     cat_label="Frontend" ;;
                gamedev)      cat_label="Game Development" ;;
                security)     cat_label="Security · Red Team" ;;
                blueteam)     cat_label="Blue Team · Defense" ;;
                reverse)      cat_label="Reverse Engineering" ;;
                productivity) cat_label="AI Productivity" ;;
                systems)      cat_label="Systems · Cloud" ;;
                compliance)   cat_label="Security Compliance" ;;
            esac
            echo "### $cat_label"
            echo ""
            echo "| Plugin | Capabilities | Description | Chains To |"
            echo "|---|---|---|---|"

            for dir in "$PLUGINS_DIR"/*/; do
                local plugin_dir="${dir%/}"
                local plugin_name="$(basename "$plugin_dir")"
                local manifest="$plugin_dir/.claude-plugin/plugin.json"
                [ -f "$manifest" ] || continue
                local pcat="$(read_str "$manifest" category)"
                [ "$pcat" = "$cat" ] || continue

                local desc="$(read_str "$manifest" description)"
                local badges="$(derive_badge_cell "$plugin_dir")"
                local chains_csv="$(read_str_array "$manifest" chains_to)"
                local chains_cell=""
                if [ -n "$chains_csv" ]; then
                    chains_cell="$(echo "$chains_csv" | sed 's|,| → /|g; s|^|/|')"
                fi

                echo "| \`/$plugin_name\` | $badges | $desc | $chains_cell |"
            done
            echo ""
        done

        echo "<!-- END-PLUGIN-TABLE -->"
    }
}

# Splice between sentinels. If sentinels are missing, append at end.
if grep -q "BEGIN-PLUGIN-TABLE" "$README"; then
    TABLE_FILE="$(mktemp)"
    emit_table > "$TABLE_FILE"
    awk -v tablefile="$TABLE_FILE" '
        BEGIN { in_block=0 }
        /<!-- BEGIN-PLUGIN-TABLE -->/ {
            while ((getline line < tablefile) > 0) print line
            close(tablefile)
            in_block=1
            next
        }
        /<!-- END-PLUGIN-TABLE -->/ { in_block=0; next }
        in_block==0 { print }
    ' "$README" > "$TMP"
    mv "$TMP" "$README"
    rm -f "$TABLE_FILE"
else
    {
        echo ""
        emit_table
    } >> "$README"
fi

echo "Regenerated plugin table in $README"
