#!/usr/bin/env bash
# ============================================================================
# regenerate-marketplace.sh
# Walks plugins/*/.claude-plugin/plugin.json and rebuilds
# .claude-plugin/marketplace.json so the repo is a Claude Code marketplace.
#
# Reads metadata from each plugin's plugin.json (name, version, description,
# category, metadata.badges, metadata.chains_to). Outputs valid JSON.
#
# Does NOT touch SKILL.md, commands/, agents/, hooks/ — those are the source
# of truth for both Claude Code and Agent Skills consumers (agentskills.io etc).
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PLUGINS_DIR="$REPO_ROOT/plugins"
OUT="$REPO_ROOT/.claude-plugin/marketplace.json"

mkdir -p "$REPO_ROOT/.claude-plugin"

# Naive JSON-string-value reader: extracts the value of a top-level key
# ("key": "value"). Good enough because plugin.json is generated by us and
# always flat for the fields we read here.
read_str() {
    local file="$1" key="$2"
    grep -E "\"$key\"[[:space:]]*:" "$file" \
        | head -1 \
        | sed -E 's/.*"'"$key"'"[[:space:]]*:[[:space:]]*"([^"]*)".*/\1/'
}

# Read a JSON array of strings on a single line: "key": ["a", "b"]
read_str_array() {
    local file="$1" key="$2"
    grep -E "\"$key\"[[:space:]]*:[[:space:]]*\[" "$file" \
        | head -1 \
        | sed -E 's/.*"'"$key"'"[[:space:]]*:[[:space:]]*\[([^]]*)\].*/\1/' \
        | tr -d ' '
}

# Derive capability badges from what actually exists on disk.
# Vocabulary: command, agent, hook, mcp, script, skill.
derive_badges() {
    local plugin_dir="$1"
    local badges=()
    [ -d "$plugin_dir/commands" ] && badges+=("command")
    [ -d "$plugin_dir/agents" ] && badges+=("agent")
    [ -f "$plugin_dir/hooks/hooks.json" ] && badges+=("hook")
    [ -f "$plugin_dir/.mcp.json" ] && badges+=("mcp")
    [ -d "$plugin_dir/scripts" ] && badges+=("script")
    [ -f "$plugin_dir/SKILL.md" ] && badges+=("skill")
    local out=""
    for b in "${badges[@]}"; do
        if [ -z "$out" ]; then out="\"$b\""; else out="$out, \"$b\""; fi
    done
    echo "$out"
}

# Begin building marketplace.json.
{
    cat <<'JSON_HEAD'
{
  "name": "skills-plugins",
  "owner": { "name": "Austin Songer", "email": "asonger.pixel@gmail.com" },
  "metadata": {
    "description": "Skills Plugins — a Claude Code marketplace + Agent Skills catalog of 60+ plugins (security, blue team, reverse engineering, frontend, backend, gamedev, compliance, productivity).",
    "version": "1.0.0"
  },
  "plugins": [
JSON_HEAD

    first=1
    for dir in "$PLUGINS_DIR"/*/; do
        plugin_dir="${dir%/}"
        plugin_name="$(basename "$plugin_dir")"
        manifest="$plugin_dir/.claude-plugin/plugin.json"
        [ -f "$manifest" ] || continue

        name="$(read_str "$manifest" name)"
        version="$(read_str "$manifest" version)"
        description="$(read_str "$manifest" description)"
        category="$(read_str "$manifest" category)"
        badges="$(derive_badges "$plugin_dir")"
        chains="$(read_str_array "$manifest" chains_to)"

        if [ $first -eq 0 ]; then echo ","; fi
        first=0

        printf '    {\n'
        printf '      "name": "%s",\n' "$name"
        printf '      "source": "./plugins/%s",\n' "$plugin_name"
        printf '      "version": "%s",\n' "$version"
        printf '      "description": "%s",\n' "$description"
        printf '      "category": "%s",\n' "$category"
        printf '      "tags": [%s],\n' "$badges"
        if [ -n "$chains" ]; then
            printf '      "metadata": { "chains_to": [%s] }\n' "$chains"
        else
            printf '      "metadata": { "chains_to": [] }\n'
        fi
        printf '    }'
    done

    cat <<'JSON_TAIL'

  ]
}
JSON_TAIL
} > "$OUT"

# Validate.
if command -v python3 >/dev/null 2>&1; then
    python3 -m json.tool "$OUT" >/dev/null
fi

echo "Regenerated $OUT ($(grep -c '"name"' "$OUT" | head -1) entries including marketplace header)"
